interface IPost {
    id: Int
    date: String
    date_gmt: String
    guid: String
    modified: String
    modified_gmt: String
    slug: String
    status: String
    type: String
    link: String
    title: String
    content: String
    excerpt: String
    author: Int
    featured_media: WordPressMedia
    comment_status: String
    ping_status: String
    sticky: Boolean
    template: String
    format: String
    meta: [String]
    categories: [Int]
    tags: [Int]
    permalink: String!
}

type Post implements IPost {
    id: Int
    date: String
    date_gmt: String
    guid: String
    modified: String
    modified_gmt: String
    slug: String
    status: String
    type: String
    link: String
    title: String
    content: String
    excerpt: String
    author: Int
    featured_media: WordPressMedia
    comment_status: String
    ping_status: String
    sticky: Boolean
    template: String
    format: String
    meta: [String]
    categories: [Int]
    tags: [Int]
    permalink: String!
}

type PostCollection {
    posts: [Post!]!
    post_types: [String]
    current_page: Int!
    total_pages: Int!
    total_posts: Int!
    per_page: Int!
    facets: [PostCollectionFacet]
}

input GetPostCollectionInput {
    per_page: Int
    page: Int
    search: String
    slug: [String]
    after: String
    modified_after: String
    author: [Int]
    author_exclude: [Int]
    before: String
    modified_before: String
    exclude: [Int]
    include: [Int]
    offset: Int
    order: [String]
    orderby: [String]
    search_columns: [String]
    status: [String]
    taxRelation: [String]
    categories: String
    categories_exclude: String
    tags: String
    tags_exclude: String
    sticky: Boolean
}

input PostInput {
    search: String
    slug: [String]
}

input PostPreviewInput {
    id: Int
    nonce: String
}

type Query {
    getPostCollection(input:GetPostCollectionInput): PostCollection
    getPostCollectionFacets(post_types: [String]): [PostCollectionFacet]
    getPostBySlug(slug: String!): Post
    getPostByID(slug: String!): Post
    getPostPreview(input: PostPreviewInput): Post
}

type PostCollectionFacet {
    type: String
    label: String
    slug: String
    values: [PostCollectionFacetValue]
}

type PostCollectionFacetValue {
    name: String
    value: String
}


