query GetSettings {
    settings {
        ...SettingsFragment
    }
}

fragment SettingsFragment on WordPressSettings {
    title
    description
    url
    email
    timezone
    date_format
    time_format
    start_of_week
    language
    use_smilies
    default_category
    default_post_format
    posts_per_page
    show_on_front
    page_on_front
    page_for_posts
    default_ping_status
    default_comment_status
    site_logo {
        ...BaseMediaFragment
    }
    site_icon
}